- README.md
Added the following: 
- Hands-On Concurrency with Rust
- Hands-On Functional Programming in Rust
- Rust Standard Library Cookbook
- Network Programming with Rust
- Rust Programming by Example
- Rust High Performance
> Added some newer Packt Books

- README.md
1. The book will be published in 2019, but there is some kind of beta on the website. I think people should know about it
2. I also added a working image for "Rust High Performance" and "Programming WebAssembly with Rust"
Have a nice time :)
> Added "Programming WebAssembly with Rust" 

- README.md
- Edit link so it does not pop up a print dialog
> Update "A Gentle Introduction To Rust " link

- README.md
The cover to Rust an Action changed a few months ago. This PR updates the link. It also updates the copy with a more relevant introduction.
> Update Rust in Action listing

- README.md
On June 19 2020, this book has been published. It is advanced, because it requires knowledge of the Rust language.
> Added 'Creative Projects for Rust Programmers' book

- README.md
Hey!
I have added the book I have been writing to the list - I have put it next to the WebAssembly one, but feel free to re-order it as you think it's best.
> Add "Zero to Production in Rust"

- README.md
Adding my book "Rust Web Development" (Manning) to the list.
> Add "Rust Web Development" book

- README.md
Please add this one to the list.
P.S.: I know this is a small contribution, but could you please add a `hacktoberfest-accepted` label on it? I really appreciate it!
> Added `Easy Rust`

- README.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. thank for considering it.
Best,
> Added Refactoring to Rust

- README.md
Please add it to this list,it'll be really useful for others.
> Added a new book from No Starch Press

- README.md
This MR adds a cover image for `Rust for Rustaceans` and also updates its status because it was already released.
> update `Rust for Rustaceans`

- README.md
> Add Rust patterns book

- README.md
> add black hat rust to README.md

- README.md
It will be first book which covers powerfull feature
> Macroses book

- README.md
Updated the image for the book, since the book is not in MEAP anymore and can be purchased as a hardcopy, PDF and ePub now.
> Rust Web Development is in production now

- README.md
> Add Rust Atomics and Locks by Mara Bos

- README.md
Hi,
Stjepan from Manning here. We have a brand new Rust title for starters. Thank you for considering it.
Best,
> Added Learn Rust in a Month of Lunches

- README.md
Add entry for Data Analysis with Rust Notebooks
> Add Data Analysis with Rust Notebooks

- README.md
See also Rustacean Station podcast episode with author, https://rustacean-station.org/episode/maxwell-flitton/.
Hi from HN!
> Add 'Rust Web Programming' by Maxwell Flitton to starter section

- README.md
Hello!
Adding a book I've recently read and immensely enjoyed.
> Add "Command-Line Rust" by Ken Youens-Clark

- README.md
Add the "Hands-on Rust" book by Herbert Wolverson
> Add "Hands-on Rust"

- README.md
> Add Introduction to Rust for Python programmers

- README.md
Thought the Burn framework might be a valid resource in the list.
Thanks for a great resource with this repo!
> Added The Burn Book

- README.md
Add missing space after header syntax so that the entry renders properly.
> Fix Code Like a Pro in Rust section header

- README.md
Hi,
we started a free book about API development with Rust. This is still a work in progress, but the completed chapters may already be useful for some. [more info](https://apatisandor.hu/blog/rust-api-dev/)
> add "API development with Rust"

- README.md
**Description**
Added a guide for those who want to understand how the Rust compiler works and learn how to make changes to it.
> Add rustc-compiler-dev-guide
